/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MessageAbi } from "./MessageAbi";
export * as factories from "./factories";
export { MessageAbi__factory } from "./factories/MessageAbi__factory";
